### ISSUE TITLE
Xbox compatible

### ISSUE THREAD

**Issue by Jeffrey68** [frappedevs/Commander#107]
Currently, us xbox players arent able to access the commander gui within our game. It would be good if you could make it so we can access it. With it not being xbox compatible we cant manage our games with the ban commands and stuff.

**Comment by 7kayoh** [comment]
We don't find supporting console users a good idea because it is not really efficient to do moderation in console, either way, console users are not able to use the chat.

**Comment by 7kayoh** [comment]
Closed due to inactivity
